package com.shoestore.entity;
// Generated Apr 20, 2024, 2:20:15â€¯PM by Hibernate Tools 4.3.6.Final

import java.util.Objects;

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * OrderDetailId generated by hbm2java
 */
@Embeddable
public class OrderDetailId implements java.io.Serializable {

	private Shoe shoe;
	private ShoeOrder shoeOrder;
	
	public OrderDetailId() {
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shoe_id", nullable = false, insertable = false, updatable = false)
	public Shoe getShoe() {
		return this.shoe;
	}

	public void setShoe(Shoe shoe) {
		this.shoe = shoe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false, insertable = false, updatable = false)
	public ShoeOrder getShoeOrder() {
		return this.shoeOrder;
	}

	public void setShoeOrder(ShoeOrder shoeOrder) {
		this.shoeOrder = shoeOrder;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((shoe == null) ? 0 : shoe.hashCode());
		result = prime * result + ((shoeOrder == null) ? 0 : shoeOrder.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderDetailId other = (OrderDetailId) obj;
		if (shoe == null) {
			if (other.shoe != null)
				return false;
		} else if (!shoe.equals(other.shoe))
			return false;
		if (shoeOrder == null) {
			if (other.shoeOrder != null)
				return false;
		} else if (!shoeOrder.equals(other.shoeOrder))
			return false;
		return true;
	}
	
}
